services:
  - type: web
    name: backendhelpstress
    env: node
    buildCommand: npm install
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: RENDER
        value: '1'
    disks:
      - name: data
        mountPath: /data
        sizeGB: 1