services:
  - type: web
    name: helpstress-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: RENDER
        value: '1'
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 